# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc935d2284d81558dbcbce1e217b91099549c059a4edf338c3c62fb6f2e1ab3963c341cd72c5b16a34da555e2959b151e2fecbf90d5c915efcc1cb30a65ae02c

test:
  secret_key_base: 8f2babe9eb3f191473ef2a1a14bc01b9fa32fd48d29f0adc58202e432a004db33f9108d15b7444404e12ae64df0f5bb98d8fb7890ddbec41930bf475f8adcbf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
